### ISSUE TITLE
Support for Win-1252

### ISSUE THREAD

**Issue by TehFlaminTaco** [L3viathan/aceto#17] opened 2017-05-22 03:57 UTC
All current commands can fit on the Windows 1252 Bytespace, it would be much golifer if it were supported.

**Comment by L3viathan** [comment] 2017-05-22 07:25
Aceto is not a codegolfing language by design, and there's no guarantee that all future commands will be in that codepage. We could introduce a command-line flag for using Windows-1252, so you'll at most get 1 byte penalty for not using pure ASCII.

**Closed as completed** 2017-05-22 09:16 UTC
Labels: feature request
